server:
  port: 8080
  servlet:
    context-path: /

spring:
  # 개발 데이터베이스 연결
  datasource:
    url: jdbc:h2:tcp://localhost/~/oath
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # 콘솔창에 sql 출력
    properties:
      hibernate:
        format_sql: true # sql 예쁘게 출력
        default_batch_fetch_size: 500 # 일대다 컬렉션 조회 시 성능 최적화 : 100 ~ 1000 권장
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정 (default 인 true 에서는 interceptor, controller, view 까지 살아있음)

  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기를 10MB 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일 크기합을 100MB 제한

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.type: trace # 콘솔창에 조건에 바인딩되는 값 및 조회 결과 출력
    com.example: debug # todo 패키지 수정

feign:
  client:
    config:
      default: # 전역 처리
        connectTimeout: 5000 # 3-way handshake 시간 제한
        readTimeout: 5000

jasypt:
  password: ${PASSWORD}

kakao:
  client:
    id: ENC(T6o3EY0Bmrmjv1QZzUtyBK3pjB6J/MZiUP+Ccwkl7aQ5hDVQik2PQoQO10hLgfXX) # REST API 키
    secret: ENC(j/M1u3e5sFY9iOXl7/I1OdNfhD8ztDsj4Ysj9AWF8CpUV+lUuwTb7Gjy9YSmvwij) # 보안 - Client Secret

token:
  secret: ENC(ebzB5G3Tc11BzxSgr1SGC7OIW/VtWUdPJImEv3YzS+cO+5eAYk0GP/ov+Mbbrbia) # 임의의 문자열
  access-token-expiration-time: 900000  # 15분 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)